# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- develop
- feature/*

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: CmdLine@2
  inputs:
    script: git submodule update --init --recursive 2>&1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  displayName: 'Build dependencies (MetroRadiance)'
  inputs:
    solution: 'deps/MetroRadiance/source/*.sln'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: 'Build dependencies (VirtualDesktop)'
  inputs:
    solution: 'deps/VirtualDesktop/source/*.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: 'Build Robock'
  inputs:
    solution: 'Source/*.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
